name: calla
description: A smartphone controlled plant watering system powered by an ESP32 and a Flutter app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.3
  percent_indicator: ^4.2.2
  liquid_progress_indicator: 
    git:
      url: https://github.com/TechDevSubhopriyo/liquid_progress_indicator.git
      ref: master # branch name
  intl: ^0.17.0
  flutter_feather_icons: ^2.0.0+1
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  get_storage: ^2.0.3
  flutter_blue: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
